# Generated by Django 6.1 on 2026-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('repository', models.URLField()),
                ('skills', models.ManyToManyField(to='portfolio.skill')),
            ],
        ),
    ]
